big_keys = true
big_keys_required = false
bombs = true
bosses = false
bosses_required = false
bottle_full = true
chest_count = true
compasses = false
fullscreen = false
fyne_scale = '1.300000'
global_hotkeys = true
goal = 1
halfmagic = true
heart_pieces = true
key_requireds = false
keys = true
keys_required = false
mail = true
maps = false
progressive_bows = true
pseudo_boots = false
shield = true
sword = true
