big_keys = true
big_keys_required = true
bombs = true
bosses = true
bosses_required = false
bottle_full = true
chest_count = true
compasses = true
fullscreen = false
fyne_scale = '1.500000'
global_hotkeys = true
goal = 0
halfmagic = true
heart_pieces = true
key_requireds = false
keys = true
keys_required = true
mail = true
maps = true
progressive_bows = true
pseudo_boots = false
shield = true
sword = true
