big_keys = false
big_keys_required = false
bombs = true
bosses = false
bosses_required = true
bottle_full = false
chest_count = false
compasses = false
fullscreen = false
fyne_scale = '1.000000'
global_hotkeys = true
goal = 0
halfmagic = true
heart_pieces = true
key_requireds = false
keys = false
keys_required = false
mail = true
maps = false
progressive_bows = true
pseudo_boots = false
shield = true
sword = true
