big_keys = false
bombs = true
bosses = false
bottle_full = true
chest_count = true
compasses = false
fullscreen = false
fyne_scale = '1.000000'
global_hotkeys = true
halfmagic = true
heart_pieces = true
keys = false
mail = true
mainwindowsizeheight = 637.46875
mainwindowsizewidth = 598.4000244140625
maps = false
shield = true
sword = true
