big_keys = false
bombs = true
bosses = false
bottle_full = true
chest_count = false
compasses = false
fullscreen = false
fyne_font = 'PressStart2P-Regular.ttf'
fyne_scale = '1.300000'
global_hotkeys = true
halfmagic = true
heart_pieces = false
keys = false
mail = true
maps = false
progressive_bows = true
pseudo_boots = false
shield = true
sword = true
