big_keys = true
bombs = true
bosses = true
bottle_full = true
chest_count = false
compasses = true
fullscreen = false
fyne_font = 'PressStart2P-Regular.ttf'
fyne_scale = '1.000000'
global_hotkeys = true
halfmagic = true
heart_pieces = true
keys = true
mail = true
maps = false
progressive_bows = true
pseudo_boots = false
shield = true
sword = true
