!/bin/bash
fyne bundle -package inventory Bat.png >> bundled.go
fyne bundle -package inventory -append Bird.png >> bundled.go
fyne bundle -package inventory -append Blue_BoomerangGray.png >> bundled.go
fyne bundle -package inventory -append Blue_Boomerang.png >> bundled.go
fyne bundle -package inventory -append Blue_Mail.png >> bundled.go
fyne bundle -package inventory -append BombGray.png >> bundled.go
fyne bundle -package inventory -append Bomb.png >> bundled.go
fyne bundle -package inventory -append BombosGray.png >> bundled.go
fyne bundle -package inventory -append Bombos.png >> bundled.go
fyne bundle -package inventory -append Book_of_MudoraGray.png >> bundled.go
fyne bundle -package inventory -append Book_of_Mudora.png >> bundled.go
fyne bundle -package inventory -append Bottle_with_Bee.png >> bundled.go
fyne bundle -package inventory -append Bottle_with_Blue_Potion.png >> bundled.go
fyne bundle -package inventory -append Bottle_with_Fairy.png >> bundled.go
fyne bundle -package inventory -append Bottle_with_Green_Potion.png >> bundled.go
fyne bundle -package inventory -append Bottle_with_Red_Potion.png >> bundled.go
fyne bundle -package inventory -append BowGray.png >> bundled.go
fyne bundle -package inventory -append Bow.png >> bundled.go
fyne bundle -package inventory -append "Bow_&_Silvers.png" >> bundled.go
fyne bundle -package inventory -append Bug-Catching_NetGray.png >> bundled.go
fyne bundle -package inventory -append Bug-Catching_Net.png >> bundled.go
fyne bundle -package inventory -append Cane_of_ByrnaGray.png >> bundled.go
fyne bundle -package inventory -append Cane_of_Byrna.png >> bundled.go
fyne bundle -package inventory -append Cane_of_SomariaGray.png >> bundled.go
fyne bundle -package inventory -append Cane_of_Somaria.png >> bundled.go
fyne bundle -package inventory -append Empty_BottleGray.png >> bundled.go
fyne bundle -package inventory -append Empty_Bottle.png >> bundled.go
fyne bundle -package inventory -append EtherGray.png >> bundled.go
fyne bundle -package inventory -append Ether.png >> bundled.go
fyne bundle -package inventory -append "Fighter's_ShieldGray.png" >> bundled.go
fyne bundle -package inventory -append "Fighter's_Shield.png" >> bundled.go
fyne bundle -package inventory -append "Fighter's_SwordGray.png" >> bundled.go
fyne bundle -package inventory -append "Fighter's_Sword.png" >> bundled.go
fyne bundle -package inventory -append Fire_RodGray.png >> bundled.go
fyne bundle -package inventory -append Fire_Rod.png >> bundled.go
fyne bundle -package inventory -append Fire_Shield.png >> bundled.go
fyne bundle -package inventory -append FlippersGray.png >> bundled.go
fyne bundle -package inventory -append Flippers.png >> bundled.go
fyne bundle -package inventory -append FluteGray.png >> bundled.go
fyne bundle -package inventory -append Flute.png >> bundled.go
fyne bundle -package inventory -append Flute_Boy.png >> bundled.go
fyne bundle -package inventory -append GanonGray.png >> bundled.go
fyne bundle -package inventory -append Ganon.png >> bundled.go
fyne bundle -package inventory -append GanonTowerGray.png >> bundled.go
fyne bundle -package inventory -append GanonTower.png >> bundled.go
fyne bundle -package inventory -append Golden_Sword.png >> bundled.go
fyne bundle -package inventory -append Green_Mail.png >> bundled.go
fyne bundle -package inventory -append Half-MagicGray.png >> bundled.go
fyne bundle -package inventory -append Half-Magic.png >> bundled.go
fyne bundle -package inventory -append HammerGray.png >> bundled.go
fyne bundle -package inventory -append Hammer.png >> bundled.go
fyne bundle -package inventory -append Heart_PieceGray.png >> bundled.go
fyne bundle -package inventory -append Heart_Piece.png >> bundled.go
fyne bundle -package inventory -append Heart_Piece1.png >> bundled.go
fyne bundle -package inventory -append Heart_Piece2.png >> bundled.go
fyne bundle -package inventory -append Heart_Piece3.png >> bundled.go
fyne bundle -package inventory -append HookshotGray.png >> bundled.go
fyne bundle -package inventory -append Hookshot.png >> bundled.go
fyne bundle -package inventory -append Ice_RodGray.png >> bundled.go
fyne bundle -package inventory -append Ice_Rod.png >> bundled.go
fyne bundle -package inventory -append LampGray.png >> bundled.go
fyne bundle -package inventory -append Lamp.png >> bundled.go
fyne bundle -package inventory -append Magic_CapeGray.png >> bundled.go
fyne bundle -package inventory -append Magic_Cape.png >> bundled.go
fyne bundle -package inventory -append Magic_MirrorGray.png >> bundled.go
fyne bundle -package inventory -append Magic_Mirror.png >> bundled.go
fyne bundle -package inventory -append Magic_PowderGray.png >> bundled.go
fyne bundle -package inventory -append Magic_Powder.png >> bundled.go
fyne bundle -package inventory -append Master_Sword.png >> bundled.go
fyne bundle -package inventory -append Mirror_Shield.png >> bundled.go
fyne bundle -package inventory -append Moon_PearlGray.png >> bundled.go
fyne bundle -package inventory -append Moon_Pearl.png >> bundled.go
fyne bundle -package inventory -append MushroomGray.png >> bundled.go
fyne bundle -package inventory -append Mushroom.png >> bundled.go
fyne bundle -package inventory -append PedestalGray.png >> bundled.go
fyne bundle -package inventory -append Pedestal.png >> bundled.go
fyne bundle -package inventory -append Pegasus_BootsGray.png >> bundled.go
fyne bundle -package inventory -append Pegasus_Boots.png >> bundled.go
fyne bundle -package inventory -append Power_GlovesGray.png >> bundled.go
fyne bundle -package inventory -append Power_Gloves.png >> bundled.go
fyne bundle -package inventory -append Pseudo_Pegasus_Boots.png >> bundled.go
fyne bundle -package inventory -append QuakeGray.png >> bundled.go
fyne bundle -package inventory -append Quake.png >> bundled.go
fyne bundle -package inventory -append Red_BoomerangGray.png >> bundled.go
fyne bundle -package inventory -append Red_Boomerang.png >> bundled.go
fyne bundle -package inventory -append Red_Mail.png >> bundled.go
fyne bundle -package inventory -append ShovelGray.png >> bundled.go
fyne bundle -package inventory -append Shovel.png >> bundled.go
fyne bundle -package inventory -append SilversGray.png >> bundled.go
fyne bundle -package inventory -append Silvers.png >> bundled.go
fyne bundle -package inventory -append Tempered_Sword.png >> bundled.go
fyne bundle -package inventory -append Titan_Mitts.png >> bundled.go
fyne bundle -package inventory -append TriforceGray.png >> bundled.go
fyne bundle -package inventory -append Triforce.png >> bundled.go
fyne bundle -package inventory -append Witch.png >> bundled.go
fyne bundle -package inventory -append Witch_Apprentice.png >> bundled.go