#!/bin/bash
fyne bundle -package inventory ../icons/Bat.png > bundled.go
fyne bundle -package inventory -append ../icons/Bird.png >> bundled.go
fyne bundle -package inventory -append ../icons/Blue_BoomerangGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Blue_Boomerang.png >> bundled.go
fyne bundle -package inventory -append ../icons/Blue_Mail.png >> bundled.go
fyne bundle -package inventory -append ../icons/BombGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Bomb.png >> bundled.go
fyne bundle -package inventory -append ../icons/BombosGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Bombos.png >> bundled.go
fyne bundle -package inventory -append ../icons/Book_of_MudoraGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Book_of_Mudora.png >> bundled.go
fyne bundle -package inventory -append ../icons/Bottle_with_Bee.png >> bundled.go
fyne bundle -package inventory -append ../icons/Bottle_with_Blue_Potion.png >> bundled.go
fyne bundle -package inventory -append ../icons/Bottle_with_Fairy.png >> bundled.go
fyne bundle -package inventory -append ../icons/Bottle_with_Green_Potion.png >> bundled.go
fyne bundle -package inventory -append ../icons/Bottle_with_Red_Potion.png >> bundled.go
fyne bundle -package inventory -append ../icons/BowGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Bow.png >> bundled.go
fyne bundle -package inventory -append ../icons/"Bow_&_Silvers.png" >> bundled.go
fyne bundle -package inventory -append ../icons/Bug-Catching_NetGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Bug-Catching_Net.png >> bundled.go
fyne bundle -package inventory -append ../icons/Cane_of_ByrnaGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Cane_of_Byrna.png >> bundled.go
fyne bundle -package inventory -append ../icons/Cane_of_SomariaGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Cane_of_Somaria.png >> bundled.go
fyne bundle -package inventory -append ../icons/Empty_BottleGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Empty_Bottle.png >> bundled.go
fyne bundle -package inventory -append ../icons/EtherGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Ether.png >> bundled.go
fyne bundle -package inventory -append ../icons/"Fighter's_ShieldGray.png" >> bundled.go
fyne bundle -package inventory -append ../icons/"Fighter's_Shield.png" >> bundled.go
fyne bundle -package inventory -append ../icons/"Fighter's_SwordGray.png" >> bundled.go
fyne bundle -package inventory -append ../icons/"Fighter's_Sword.png" >> bundled.go
fyne bundle -package inventory -append ../icons/Fire_RodGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Fire_Rod.png >> bundled.go
fyne bundle -package inventory -append ../icons/Fire_Shield.png >> bundled.go
fyne bundle -package inventory -append ../icons/FlippersGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Flippers.png >> bundled.go
fyne bundle -package inventory -append ../icons/FluteGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Flute.png >> bundled.go
fyne bundle -package inventory -append ../icons/Flute_Boy.png >> bundled.go
fyne bundle -package inventory -append ../icons/GanonGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Ganon.png >> bundled.go
fyne bundle -package inventory -append ../icons/GanonTowerGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/GanonTower.png >> bundled.go
fyne bundle -package inventory -append ../icons/Golden_Sword.png >> bundled.go
fyne bundle -package inventory -append ../icons/Green_Mail.png >> bundled.go
fyne bundle -package inventory -append ../icons/Half-MagicGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Half-Magic.png >> bundled.go
fyne bundle -package inventory -append ../icons/HammerGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Hammer.png >> bundled.go
fyne bundle -package inventory -append ../icons/Heart_PieceGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Heart_Piece.png >> bundled.go
fyne bundle -package inventory -append ../icons/Heart_Piece1.png >> bundled.go
fyne bundle -package inventory -append ../icons/Heart_Piece2.png >> bundled.go
fyne bundle -package inventory -append ../icons/Heart_Piece3.png >> bundled.go
fyne bundle -package inventory -append ../icons/HookshotGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Hookshot.png >> bundled.go
fyne bundle -package inventory -append ../icons/Ice_RodGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Ice_Rod.png >> bundled.go
fyne bundle -package inventory -append ../icons/LampGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Lamp.png >> bundled.go
fyne bundle -package inventory -append ../icons/Magic_CapeGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Magic_Cape.png >> bundled.go
fyne bundle -package inventory -append ../icons/Magic_MirrorGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Magic_Mirror.png >> bundled.go
fyne bundle -package inventory -append ../icons/Magic_PowderGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Magic_Powder.png >> bundled.go
fyne bundle -package inventory -append ../icons/Master_Sword.png >> bundled.go
fyne bundle -package inventory -append ../icons/Mirror_Shield.png >> bundled.go
fyne bundle -package inventory -append ../icons/Moon_PearlGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Moon_Pearl.png >> bundled.go
fyne bundle -package inventory -append ../icons/MushroomGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Mushroom.png >> bundled.go
fyne bundle -package inventory -append ../icons/PedestalGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Pedestal.png >> bundled.go
fyne bundle -package inventory -append ../icons/Pegasus_BootsGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Pegasus_Boots.png >> bundled.go
fyne bundle -package inventory -append ../icons/Power_GlovesGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Power_Gloves.png >> bundled.go
fyne bundle -package inventory -append ../icons/Pseudo_Pegasus_Boots.png >> bundled.go
fyne bundle -package inventory -append ../icons/QuakeGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Quake.png >> bundled.go
fyne bundle -package inventory -append ../icons/Red_BoomerangGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Red_Boomerang.png >> bundled.go
fyne bundle -package inventory -append ../icons/Red_Mail.png >> bundled.go
fyne bundle -package inventory -append ../icons/ShovelGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Shovel.png >> bundled.go
fyne bundle -package inventory -append ../icons/SilversGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Silvers.png >> bundled.go
fyne bundle -package inventory -append ../icons/Tempered_Sword.png >> bundled.go
fyne bundle -package inventory -append ../icons/Titan_Mitts.png >> bundled.go
fyne bundle -package inventory -append ../icons/TriforceGray.png >> bundled.go
fyne bundle -package inventory -append ../icons/Triforce.png >> bundled.go
fyne bundle -package inventory -append ../icons/Witch.png >> bundled.go
fyne bundle -package inventory -append ../icons/Witch_Apprentice.png >> bundled.go