!/bin/bash
fyne bundle -package tappable_icons ArmosGray.png > bundled.go
fyne bundle -package tappable_icons -append Armos.png >> bundled.go
fyne bundle -package tappable_icons -append ArrghusGray.png >> bundled.go
fyne bundle -package tappable_icons -append Arrghus.png >> bundled.go
fyne bundle -package tappable_icons -append BlindGray.png >> bundled.go
fyne bundle -package tappable_icons -append Blind.png >> bundled.go
fyne bundle -package tappable_icons -append Blue_CrystalGray.png >> bundled.go
fyne bundle -package tappable_icons -append Blue_Crystal.png >> bundled.go
fyne bundle -package tappable_icons -append Blue_Red_PendantGray.png >> bundled.go
fyne bundle -package tappable_icons -append Blue_Red_Pendant.png >> bundled.go
fyne bundle -package tappable_icons -append Green_PendantGray.png >> bundled.go
fyne bundle -package tappable_icons -append Green_Pendant.png >> bundled.go
fyne bundle -package tappable_icons -append HelmasaurGray.png >> bundled.go
fyne bundle -package tappable_icons -append Helmasaur.png >> bundled.go
fyne bundle -package tappable_icons -append KholdstareGray.png >> bundled.go
fyne bundle -package tappable_icons -append Kholdstare.png >> bundled.go
fyne bundle -package tappable_icons -append LanmolasGray.png >> bundled.go
fyne bundle -package tappable_icons -append Lanmolas.png >> bundled.go
fyne bundle -package tappable_icons -append MoldormGray.png >> bundled.go
fyne bundle -package tappable_icons -append Moldorm.png >> bundled.go
fyne bundle -package tappable_icons -append MothulaGray.png >> bundled.go
fyne bundle -package tappable_icons -append Mothula.png >> bundled.go
fyne bundle -package tappable_icons -append Red_CrystalGray.png >> bundled.go
fyne bundle -package tappable_icons -append Red_Crystal.png >> bundled.go
fyne bundle -package tappable_icons -append TrinexxGray.png >> bundled.go
fyne bundle -package tappable_icons -append Trinexx.png >> bundled.go
fyne bundle -package tappable_icons -append VitreousGray.png >> bundled.go
fyne bundle -package tappable_icons -append Vitreous.png >> bundled.go