big_keys_required_bool = true
'blue boomerang_current_int' = 0
bomb_current_int = 0
bombos_obtained_bool = false
bombos_textcurrent_int = 0
'book of mudora_current_int' = 0
bosses_required_bool = false
'bottle 1_current_int' = 0
'bottle 2_current_int' = 0
'bottle 3_current_int' = 0
'bottle 4_current_int' = 0
'bottle total_current_int' = 0
'bottle total_number_int' = 0
bow_current_int = 0
bug-net_current_int = 0
'cane of byrna_current_int' = 0
'cane of somaria_current_int' = 0
compasses_required_bool = true
ct_agahnim1_current_int = 0
ct_chest_number_int = 0
ct_keys_number_int = 0
dp_bigkey_current_int = 0
dp_boss_current_int = 1
dp_chest_number_int = 2
dp_compass_current_int = 0
dp_keys_number_int = 0
dp_map_current_int = 0
dp_prize_current_int = 0
dp_prize_obtained_bool = false
ep_bigkey_current_int = 0
ep_boss_current_int = 0
ep_chest_number_int = 3
ep_compass_current_int = 0
ep_keys_number_int = 0
ep_map_current_int = 0
ep_prize_current_int = 0
ep_prize_obtained_bool = false
ether_obtained_bool = false
ether_textcurrent_int = 0
'fire rod_current_int' = 0
flippers_current_int = 1
flute_current_int = 2
'ganon goal_current_int' = 8
'ganon goal_obtained_bool' = false
'ganon tower goal_current_int' = 7
'ganon tower goal_obtained_bool' = false
gloves_current_int = 0
goal_int = 0
gt_agahnim2_current_int = 0
gt_bigkey_current_int = 0
gt_chest_number_int = 20
gt_compass_current_int = 0
gt_keys_number_int = 0
gt_map_current_int = 0
half-magic_current_int = 0
hammer_current_int = 0
hc_chest_number_int = 6
hc_keys_number_int = 0
hc_map_current_int = 0
'heart pieces_current_int' = 0
hookshot_current_int = 0
'ice rod_current_int' = 0
ip_bigkey_current_int = 0
ip_boss_current_int = 7
ip_chest_number_int = 3
ip_compass_current_int = 0
ip_keys_number_int = 0
ip_map_current_int = 0
ip_prize_current_int = 0
ip_prize_obtained_bool = false
keys_required_bool = true
lamp_current_int = 0
'magic cape_current_int' = 0
'magic mirror_current_int' = 0
'magic powder_current_int' = 2
mail_current_int = 0
maps_required_bool = true
mm_bigkey_current_int = 0
mm_boss_current_int = 8
mm_chest_number_int = 2
mm_compass_current_int = 0
mm_keys_number_int = 0
mm_map_current_int = 0
mm_prize_current_int = 0
mm_prize_obtained_bool = true
'moon pearl_current_int' = 0
mushroom_current_int = 4
'non-progressive bow_current_int' = 0
pd_bigkey_current_int = 0
pd_boss_current_int = 3
pd_chest_number_int = 5
pd_compass_current_int = 0
pd_keys_number_int = 0
pd_map_current_int = 0
pd_prize_current_int = 0
pd_prize_obtained_bool = false
'pedestal goal_current_int' = 0
'pegasus boots_current_int' = 0
progressive_bows_bool = true
'pseudo boots_current_int' = 0
pseudo_boots_bool = false
quake_obtained_bool = false
quake_textcurrent_int = 0
'red boomerang_current_int' = 0
shield_current_int = 0
shovel_current_int = 2
sp_bigkey_current_int = 0
sp_boss_current_int = 4
sp_chest_number_int = 6
sp_compass_current_int = 0
sp_keys_number_int = 0
sp_map_current_int = 0
sp_prize_current_int = 0
sp_prize_obtained_bool = false
sw_bigkey_current_int = 0
sw_boss_current_int = 5
sw_chest_number_int = 2
sw_compass_current_int = 0
sw_keys_number_int = 0
sw_map_current_int = 0
sw_prize_current_int = 0
sw_prize_obtained_bool = false
sword_current_int = 0
th_bigkey_current_int = 0
th_boss_current_int = 2
th_chest_number_int = 2
th_compass_current_int = 0
th_keys_number_int = 0
th_map_current_int = 0
th_prize_current_int = 0
th_prize_obtained_bool = false
tr_bigkey_current_int = 0
tr_boss_current_int = 9
tr_chest_number_int = 5
tr_compass_current_int = 0
tr_keys_number_int = 0
tr_map_current_int = 0
tr_prize_current_int = 0
tr_prize_obtained_bool = false
'triforce goal_current_int' = 0
tt_bigkey_current_int = 0
tt_boss_current_int = 6
tt_chest_number_int = 4
tt_compass_current_int = 0
tt_keys_number_int = 0
tt_map_current_int = 0
tt_prize_current_int = 0
tt_prize_obtained_bool = false
